USE Filmer;


INSERT INTO Filmer (Titel, Genre, Regissör, År)
VALUES
  ('The Godfather', 'Crime', 'Francis Ford Coppola', 1972),
  ('The Godfather: Part II', 'Crime', 'Francis Ford Coppola', 1974),
  ('The Godfather: Part III', 'Crime', 'Francis Ford Coppola', 1990),
  ('Star Wars: Episode IV - A New Hope', 'Sci-Fi', 'George Lucas', 1977),
  ('Star Wars: Episode V - The Empire Strikes Back', 'Sci-Fi', 'Irvin Kershner', 1980),
  ('Star Wars: Episode VI - Return of the Jedi', 'Sci-Fi', 'Richard Marquand', 1983),
  ('Star Wars: Episode I - The Phantom Menace', 'Sci-Fi', 'George Lucas', 1999),
  ('Star Wars: Episode II - Attack of the Clones', 'Sci-Fi', 'George Lucas', 2002),
  ('Star Wars: Episode III - Revenge of the Sith', 'Sci-Fi', 'George Lucas', 2005),
  ('Star Wars: Episode VII - The Force Awakens', 'Sci-Fi', 'J.J. Abrams', 2015),
  ('Star Wars: Episode VIII - The Last Jedi', 'Sci-Fi', 'Rian Johnson', 2017),
  ('Star Wars: Episode IX - The Rise of Skywalker', 'Sci-Fi', 'J.J. Abrams', 2019),
  ('National Lampoon''s Animal House', 'Comedy', 'John Landis', 1978),
  ('Jaws', 'Thriller', 'Steven Spielberg', 1975),
  ('Close Encounters of the Third Kind', 'Sci-Fi', 'Steven Spielberg', 1977),
  ('Raiders of the Lost Ark', 'Adventure', 'Steven Spielberg', 1981),
  ('E.T. the Extra-Terrestrial', 'Sci-Fi', 'Steven Spielberg', 1982),
  ('Jurassic Park', 'Sci-Fi', 'Steven Spielberg', 1993),
  ('Schindler''s List', 'Drama', 'Steven Spielberg', 1993),
  ('Saving Private Ryan', 'War', 'Steven Spielberg', 1998),
  ('Catch Me If You Can', 'Biography', 'Steven Spielberg', 2002),
  ('The Terminal', 'Comedy', 'Steven Spielberg', 2004),
  ('Lincoln', 'Biography', 'Steven Spielberg', 2012),
  ('Bridge of Spies', 'Drama', 'Steven Spielberg', 2015),
  ('The Post', 'Biography', 'Steven Spielberg', 2017),
  ('Ready Player One', 'Sci-Fi', 'Steven Spielberg', 2018),
  ('Indiana Jones and the Temple of Doom', 'Adventure', 'Steven Spielberg', 1984),
  ('Indiana Jones and the Last Crusade', 'Adventure', 'Steven Spielberg', 1989),
  ('Indiana Jones and the Kingdom of the Crystal Skull', 'Adventure', 'Steven Spielberg', 2008),
  ('The Color Purple', 'Drama', 'Steven Spielberg', 1985),
  ('Empire of the Sun', 'Drama', 'Steven Spielberg', 1987),
  ('Always', 'Fantasy', 'Steven Spielberg', 1989),
  ('Hook', 'Adventure', 'Steven Spielberg', 1991),
  ('A.I. Artificial Intelligence', 'Sci-Fi', 'Steven Spielberg', 2001),
  ('Minority Report', 'Action', 'Steven Spielberg', 2002),
  ('War of the Worlds', 'Sci-Fi', 'Steven Spielberg', 2005),
  ('Munich', 'Drama', 'Steven Spielberg', 2005),
  ('The Adventures of Tintin', 'Animation', 'Steven Spielberg', 2011),
  ('The BFG', 'Adventure', 'Steven Spielberg', 2016),
  ('The Sugarland Express', 'Crime', 'Steven Spielberg', 1974),
  ('1941', 'Comedy', 'Steven Spielberg', 1979),
  ('Twilight Zone: The Movie', 'Fantasy', 'Steven Spielberg', 1983),
  ('The Color Purple', 'Drama', 'Steven Spielberg', 1985),
  ('Empire of the Sun', 'Drama', 'Steven Spielberg', 1987),
  ('Always', 'Fantasy', 'Steven Spielberg', 1989),
  ('Hook', 'Adventure', 'Steven Spielberg', 1991),
  ('A.I. Artificial Intelligence', 'Sci-Fi', 'Steven Spielberg', 2001),
  ('Minority Report', 'Action', 'Steven Spielberg', 2002),
  ('War of the Worlds', 'Sci-Fi', 'Steven Spielberg', 2005),
  ('Munich', 'Drama', 'Steven Spielberg', 2005),
  ('National Lampoon''s Vacation', 'Comedy', 'Harold Ramis', 1983),
  ('National Lampoon''s European Vacation', 'Comedy', 'Amy Heckerling', 1985),
  ('National Lampoon''s Christmas Vacation', 'Comedy', 'Jeremiah S. Chechik', 1989),
  ('National Lampoon''s Loaded Weapon 1', 'Comedy', 'Gene Quintano', 1993),
  ('National Lampoon''s Senior Trip', 'Comedy', 'Kelly Makin', 1995),
  ('National Lampoon''s Van Wilder', 'Comedy', 'Walt Becker', 2002),
  ('National Lampoon''s Pledge This!', 'Comedy', 'William Heins, Strathford Hamilton', 2006),
  ('National Lampoon''s Ratko: The Dictator''s Son', 'Comedy', 'Savage Steve Holland', 2009);

